In [18]:
from pathlib import Path
import pandas as pd

In [19]:
# raiz do projeto (WINOV)
ROOT = Path().resolve().parents[0]

# caminho dos dados brutos
RAW = ROOT / "data" / "raw"

# leitura do CSV (nome REAL do arquivo)
df = pd.read_csv(
    RAW / "banco_vendas_exemplo_teste.csv",
    sep=",",
    encoding="utf-8"
)

df.head()

,Codigo,DataVenda,CodFilial,CodCliente,NomeCliente,CidadeCliente,EstadoCliente,CodProduto,DescricaoProdutos,CodVendedor,NomeVendedor,ValorBruto,ValorLiquido,Desconto,Variação
0,1,2024-12-24 17:32:18,10,1010,ASSOC. DAS PIONEIRAS SOCIAIS,São Paulo,SP,951236,PORTA PALETE,4567,Camila Martins,5928.94,4921.02,1007.9198,0.17
1,2,2024-09-01 13:41:45,10,1010,ASSOC. DAS PIONEIRAS SOCIAIS,São Paulo,SP,325874,SUPORTE PORTA,4879,Vanessa Correia,7064.33,5863.39,1200.9361,0.17
2,3,2025-07-13 15:23:21,11,1155,HEMOCLIN CLINICA HEMATOLOGICA LTDA,Florianópolis,SC,753698,PALETE PEQUENO,5514,Priscila Campos,9269.71,7693.86,1575.8507,0.17
3,4,2025-02-04 20:03:30,12,1254,EXLAB - LABORATORIO DE ANALISES CLINICAS LTDA,Goiânia,GO,357412,PALETE MEDIO,2425,Bruno Rodrigues,5928.94,4921.02,1007.9198,0.17
4,5,2025-04-16 20:24:18,13,1315,LEMOS LAB. DE ANALISES CLINICAS S/S LTDA,Natal,RN,357896,PALETE GRANDE,6568,Leandro Pinto,3193.62,2650.70,542.9154,0.17

In [20]:
df.isnull().sum()

Codigo               0
DataVenda            0
CodFilial            0
CodCliente           0
NomeCliente          0
CidadeCliente        0
EstadoCliente        0
CodProduto           0
DescricaoProdutos    0
CodVendedor          0
NomeVendedor         0
ValorBruto           0
ValorLiquido         0
Desconto             0
Variação             0
dtype: int64

In [21]:
df.shape

(1219, 15)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1219 entries, 0 to 1218
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Codigo             1219 non-null   int64
 1   DataVenda          1219 non-null   str
 2   CodFilial          1219 non-null   int64
 3   CodCliente         1219 non-null   int64
 4   NomeCliente        1219 non-null   str
 5   CidadeCliente      1219 non-null   str
 6   EstadoCliente      1219 non-null   str
 7   CodProduto         1219 non-null   int64
 8   DescricaoProdutos  1219 non-null   str
 9   CodVendedor        1219 non-null   int64
 10  NomeVendedor       1219 non-null   str
 11  ValorBruto         1219 non-null   float64
 12  ValorLiquido       1219 non-null   float64
 13  Desconto           1219 non-null   float64
 14  Variação           1219 non-null   float64
dtypes: float64(4), int64(5), str(6)
memory usage: 143.0 KB

In [23]:
df.duplicated().sum()

np.int64(2)

In [24]:
df[df.duplicated(keep=False)]

,Codigo,DataVenda,CodFilial,CodCliente,NomeCliente,CidadeCliente,EstadoCliente,CodProduto,DescricaoProdutos,CodVendedor,NomeVendedor,ValorBruto,ValorLiquido,Desconto,Variação
645,646,2025-04-09 10:30:31,23,2388,DIAFARMA PROD. P/LABORATORIOS LTDA,Fortaleza,CE,258369,EIXO 48X48,1596,Mateus Carvalho,4038.92,3392.69,646.2272,0.16
646,646,2025-04-09 10:30:31,23,2388,DIAFARMA PROD. P/LABORATORIOS LTDA,Fortaleza,CE,258369,EIXO 48X48,1596,Mateus Carvalho,4038.92,3392.69,646.2272,0.16
746,746,2024-08-22 02:09:17,18,1887,LABORCENTER FRANCAII,João Pessoa,PB,123798,EIXO 24X48,2425,Bruno Rodrigues,13308.75,11445.53,1863.2250,0.14
747,746,2024-08-22 02:09:17,18,1887,LABORCENTER FRANCAII,João Pessoa,PB,123798,EIXO 24X48,2425,Bruno Rodrigues,13308.75,11445.53,1863.2250,0.14

In [28]:
print("Antes:", df.shape)
df_clean = df.drop_duplicates()
print("Depois:", df_clean.shape)

Antes: (1219, 15)
Depois: (1217, 15)

In [29]:
df_clean.duplicated().sum()

np.int64(0)

In [30]:
df_processed = df_clean.copy()

df_processed.to_csv(
    ROOT / "data" / "processed" / "vendas_processed.csv",
    index=False
)